### ISSUE TITLE
boon vs. jsonschema?

### ISSUE THREAD

**Issue by gadomski** [developmentseed/cql2-rs#20]
Curiosity question, was there a reason for picking [boon](https://github.com/santhosh-tekuri/boon) over [jsonschema](https://github.com/Stranger6667/jsonschema-rs)? I don't have a strong preference, but **jsonschema** does _feel_ a bit more built-out and mature. Disclosure: I've used **jsonschema** in https://github.com/stac-utils/stac-rs and have my issues w/ it (mostly it's blocking-only reference resolution) but it's fit for purpose, at least.

**Comment by lovrozagar** [comment]
Hi @gadomski ,

The project uses Boon instead of JSON Schema primarily for its lightweight nature and performance benefits, which align better with the parsing and validation requirements of the CQL2 filter language. JSON Schema’s complexity and blocking reference resolution may introduce unnecessary overhead. Boon offers a simpler, more efficient alternative, enhancing the overall development experience for this specific use case.

**Comment by gadomski** [comment]
Thanks @lovrozagar! Curious about

> performance benefits

[The jsonschema benchmarks page](https://github.com/Stranger6667/jsonschema-rs/tree/master/crates/benchmark-suite) has **jsonschema** on rough parity with **boon**, with speedups in some cases. Obviously, benchmarks should be taken with significant salt 🧂 , and so I'd be interested to see other comparisons. Do any exist from the **boon** side (I did a brief search and couldn't find any)?

> JSON Schema’s ... blocking reference resolution may introduce unnecessary overhead.

I _think_ that's not a problem for us in **cql2-rs** because we know we won't need to validate any unknown schemas.

Again, not arguing for or against necessarily, just want to make sure I understand the decisions space.

**Comment by bitner** [comment]
jsonschema doesn't fully support json schema  2020-12 and wasn't able to use the cql2.json schema and boon worked fine with it
